# Usamos o Nginx, um servidor web super leve
FROM nginx:alpine

# Copiamos o nosso HTML para a pasta pública do servidor
COPY index.html /usr/share/nginx/html/

# Expomos a porta padrão de sites
EXPOSE 80