version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: ufape_mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: ufape_reserva_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: